language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build

deploy:
  provider: pypi
  username: __token__
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  skip_existing: true
  edge: true # opt in to dpl v2
